version: 2.1

executors:
  environment:
    docker:
      - image: cimg/node:20.0

jobs:
  test:
    executor: environment
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package-lock.json" }}
            - v1-deps-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Lint
          command: npm run lint
  build:
    executor: environment
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Setup environment variables
          command: echo 'export TAG="0.1.$CIRCLE_BUILD_NUM"' >> "$BASH_ENV"
      - run:
          name: Build image
          command: docker build -t achori/recipes-web:$TAG .
      - run:
          name: Push image
          command: |
            echo $DOCKERHUB_ACCESS_TOKEN | docker login -u achori --password-stdin

            docker push achori/recipes-web:$TAG
            if [ $CIRCLE_BRANCH == "master" ] || [ $CIRCLE_BRANCH == "preprod" ] || [ $CIRCLE_BRANCH == "develop" ];
            then
              docker tag achori/recipes-web:$TAG achori/recipes-web:$CIRCLE_BRANCH
              docker push achori/recipes-web:$CIRCLE_BRANCH
            fi
  release:
    executor: environment
    steps:
      - run: echo released

workflow:
  ci_cd:
    jobs:
      - test
      - build
